core.go
go.mod
internal/wscore/wscore.go
ws.go

Add stubbed API

---

.github/test/Dockerfile
.gitignore
opcode.go
opcode_string.go
statuscode.go
statuscode_string.go
websocket.go
websocket_test.go

Closes #7
Will not keep these though as they are janky to integrate in CI,
not documented well and very slow. They were extremely useful for
making sure my implementation works right now but I'd rather have my own Go tests.

Integrate autobahn tests

---

README.md
accept.go
accept_test.go
datatype.go
datatype_string.go
dial.go
dial_test.go
example_test.go
header_test.go
json.go
statuscode.go
test.sh
websocket.go
websocket_test.go

Improve API and test coverage

---

websocket_test.go
xor.go
xor_test.go

Closes #76
```
benchmark                      old ns/op     new ns/op     delta
BenchmarkXOR/2/basic-2         5.43          5.46          +0.55%
BenchmarkXOR/2/fast-2          6.42          6.39          -0.47%
BenchmarkXOR/16/basic-2        17.0          17.1          +0.59%
BenchmarkXOR/16/fast-2         17.7          16.6          -6.21%
BenchmarkXOR/32/basic-2        30.6          30.7          +0.33%
BenchmarkXOR/32/fast-2         19.3          17.8          -7.77%
BenchmarkXOR/512/basic-2       448           445           -0.67%
BenchmarkXOR/512/fast-2        98.7          61.2          -37.99%
BenchmarkXOR/4096/basic-2      3487          3498          +0.32%
BenchmarkXOR/4096/fast-2       697           379           -45.62%
BenchmarkXOR/16384/basic-2     13894         13952 …
```

Super fast XOR

---

internal/bpool/bpool.go
internal/bpool/bpool_test.go
wsjson/wsjson.go
wspb/wspb.go

Pool buffers in wspb and wsjson

---

accept.go
dial.go
dial_test.go
export_test.go
websocket.go
websocket_test.go

Closes #88
Thanks again for the bug report @propertyscott.

Add WebSocket masking and correctly use Sec-WebSocket-Key in client

---

example_test.go
websocket.go
websocket_test.go

@ssmith so I added a test for the issue you reported to me.
It passes. Does your code look any different?

Add CloseRead and closeError test

---

netconn.go
websocket.go
websocket_test.go

Add NetConn adapter and protect against Reader after CloseRead

---

statuscode.go
websocket.go

Update Conn.Close docs

---

ci/test.sh
websocket.go

Ignore write error when echoing close frame

---

netconn.go
websocket.go
websocket_test.go

Add msgType parameter to NetConn adapter

---

README.md
docs/CONTRIBUTING.md
docs/ISSUE_TEMPLATE.md
docs/PULL_REQUEST_TEMPLATE.md

Make CONTRIBUTING.md more visible

---

.circleci/config.yml
README.md
accept.go
accept_test.go
ci/image/Dockerfile
ci/test.sh
dial.go
dial_test.go
docs/CONTRIBUTING.md
example_echo_test.go
example_test.go
export_test.go
go.mod
go.sum
header_test.go
netconn.go
statuscode.go
statuscode_test.go
websocket.go
websocket_test.go

Closes #112
Closes #117
Closes #97

Improve tests

---

ci/test.sh
cmp_test.go
docs/CONTRIBUTING.md
go.mod
go.sum
websocket.go
websocket_test.go

Simplify tests

---

netconn.go
websocket_test.go

Closes #125
Minor API change, will need to document clearly in release notes.

Modify NetConn to take a context as the first argument

---

README.md
example_test.go

Add a CloseError example

---

.circleci/config.yml
README.md
accept.go
dial.go
example_echo_test.go
example_test.go
export_test.go
go.mod
go.sum
header.go
netconn.go
statuscode.go
websocket.go
websocket_test.go
wsjson/wsjson.go
wspb/wspb.go

Closes #134
httpguts is an almost direct port of https://github.com/golang/net/blob/master/http/httpguts/httplex.go#L106

Remove extra dependencies

---

ci/wasm.sh
conn.go
conn_common.go
websocket_js.go

Fix unaligned 64 bit atomic loads on 32 bit platforms

---

.github/workflows/ci.yml
assert_test.go
ci/wasm.sh
conn.go
conn_common.go
conn_test.go
frame_test.go
handshake.go
handshake_test.go

math/rand was being used inappropiately and did not have
a init function for every file it was used in.
crypto/rand was also being used incorrectly within
makeSecWebSocketKey().

Improve usage of math/rand versus crypto/rand

---

README.md
assert_test.go
conn_test.go
doc.go
example_test.go
frame.go
frame_test.go
internal/assert/assert.go
websocket_js_test.go

Will make it much more convenient and less error prone to access
the StatusCode of a *CloseError.
Related #128 
Precedent for this is in https://godoc.org/gocloud.dev/gcerrors#Code
It's annoying to do the whole xerrors.As dance when you only want to access the status code.
I was only blocked on the name for this but I think `CloseStatus` is nice.
@ammar @coadler

Add websocket.CloseStatus

---

read.go
write.go

Ensure connection is closed at all error points

---

accept.go
accept_test.go
example_test.go

Add OriginPatterns to AcceptOptions

---

conn_test.go
internal/test/wstest/pipe.go

Will deal with #197 before merging.

Simplify wstest.Pipe

---

README.md
accept.go
conn_test.go
examples/chat/README.md

Should prefer it over AcceptOrigins with []string{"*"}
for explicitness.

Undeprecate InsecureSkipVerify

---

write.go

Closes #248
Luckily, due to the 5s timeout on the close handshake, this would have
had very minimal effects on anyone in production.

write.go: Fix deadlock in writeFrame

---

accept.go
dial.go

`opts = &*opts` is a no-op.
See: https://staticcheck.io/docs/checks#SA4001

Clone options

---

dial.go
dial_test.go

Copy HTTP client

---

examples/echo/server.go

this seems like a pointless newline, correct me if I am wrong.
furthermore, I would recommend using [wsl](https://github.com/bombsimon/wsl) in CI to automatically detect these kinds of errors in the future.
wsl is included in [golangci-lint](https://golangci-lint.run/usage/linters/), which is the defacto golang linter, which it seems like you [don't use currently](https://github.com/nhooyr/websocket/blob/master/ci/lint.sh).

removing bad newline

---

accept.go
accept_test.go
dial.go

WebSocket implementation in chromium rejects
ws connections in case server side responses with
`Sec-WebSocket-Protocol` header which value does
not match one of the values sent in the same header by client
In case you use subprotocols to send case-sensitive text
(for example, auth tokens) you end up with inability
to establish websocket connection from chromium.
Initialize websocket like this:
```go
websocketOptions := &websocket.AcceptOptions{}
if subProtocol := r.Header.Get("Sec-Websocket-Protocol"); subProtocol != "" {
websocketOptions.Subprotocols = []string{subProtocol}
}
...
ws, err := websocket.Accept(w, r, websocketOptions)
...
```
After that try to establish connection from javascript in chromium (my current version is `87.0.4280.88`):
```js
var ws = new WebSocket(url, "ToKeN") …
```

Preserve client case for selected subprotocol

---

accept.go
accept_test.go
ci/test.sh
dial.go
dial_test.go
examples/echo/server.go
internal/test/wstest/pipe.go

There were a few PRs merged into the master branch that were then not
merged into the dev branch. This branch merges those changes in cleanly.
- #261
- #266
- #273

Merge master into dev

---

conn_test.go
netconn.go
read.go

netconn.go: Disable read limit on WebSocket

---

ci/container/Dockerfile
conn_notjs.go
read.go

A double channel close panic was possible if a peer sent back multiple
pongs for every ping.
If the second pong arrived before the ping goroutine deleted its channel
from the map, the channel would be closed twice and so a panic would
ensue.
This fixes that by having the read goroutine send on the ping
goroutine's channel rather than closing it.
Reported via email by Tibor Kálmán @kalmant
Please update to the new release ASAP!
cc @noramehesz

Fix DOS attack from malicious pongs

---

read.go

Hi, fixing what looks like a grammatical issue?

fixing grammar

---

go.mod
go.sum

Fixes https://github.com/nhooyr/websocket/issues/359

Update Go module version to 1.18

---

autobahn_test.go
conn_test.go
dial.go
dial_test.go
doc.go
examples/chat/chat.go
read.go

This addresses #370 by switched out `ioutil` methods with their `io` and `os` equivalents.

Migrate from deprecated `io/ioutil`

---

close.go
close_go113.go
close_go116.go

Go 1.16 has introduced net.ErrClosed, which should be returned/wrapped when an
I/O call is performed on a network connection which has already been closed.
This is useful to avoid cluttering logs with messages like "failed to close
WebSocket: already wrote close".
Closes: https://github.com/nhooyr/websocket/issues/286

Use net.ErrClosed

---

dial.go
dial_test.go

When the ctx is nil, http.NewRequestWithContext returns a "net/http: nil Context" error and a nil request. In this case, the dial function panics because it assumes the req is never nil. This checks the returning error and returns it, so that callers get an error instead of a panic in that scenario.

Fix dial panic when ctx is nil

---

dial.go
dial_test.go

The standard `http.Request.Host` field allows to override the `Host` header that is sent with the HTTP request (`URL.Host` is used by default). Such option can be useful in various scenarios, for example when running behind some proxy server.
This patch extends the `DialOptions` struct with `Host` field that basically does the same.

Extend DialOptions to allow Host header override

---

conn_test.go
netconn.go
netconn_js.go
netconn_notjs.go

Currently, RemoteAddr() and LocalAddr() are mocked. This change allow the real RemoteAddr() and LocalAddr() to be used.

Returns real remote and local address instead mocked

---

accept.go
accept_test.go
compress.go
dial.go
internal/test/assert/assert.go
ws_js.go

I ran into a server this morning that was being extra-super-duper explicit and specifying `server_max_window_bits=15`, so I started digging into the RFC and the negotiation code... These are the changes I would like to make:
1. Client allows server to specify `server_max_window_bits`: The server may use a smaller sliding window for compression without affecting the client's decompression.
2. Server allows client to specify `server_max_window_bits=15`: Although the server can't support a smaller sliding window at the moment, it doesn't hurt to accept the specification of 15 bits from a client.
3. Server declines unacceptable compression offers without rejecting the request and selects the first acceptable offer: According to the RFC, the client may send multiple offers in its preferential …

Make compression negotiation more lenient

---

accept.go
accept_test.go
internal/test/xrand/xrand.go

Client "Sec-WebSocket-Key" should be a valid 16 byte base64 encoded nonce. If the header is not valid, the server should reject the client.

Reject invalid "Sec-WebSocket-Key" headers from clients

---

internal/examples/chat/README.md
internal/examples/chat/main.go
internal/examples/echo/README.md
internal/examples/echo/main.go

the websocket protocol require the protocol on the url to be `ws` not `http`, then we must log the url which is for websocket.

Change protocol in docs and logs from http to ws

---

netconn.go

On some 32-bit architectures, 64-bit atomic operations panic when the value is not aligned properly.
In this package, this causes netConn operations to panic when compiling with `GOARCH=386`, since netConn does atomic operations with int64 values in the netConn struct (namely, with readExpired and writeExpired):
```
runtime/internal/atomic.panicUnaligned()
.../go1.22/src/runtime/internal/atomic/unaligned.go:8 +0x2d
runtime/internal/atomic.Load64(0x90a011c)
.../go1.22/src/runtime/internal/atomic/atomic_386.s:225 +0x10
nhooyr.io/websocket.(*netConn).read(0x90a00f0, {0x9180000, 0x8000, 0x8000})
.../go/pkg/mod/nhooyr.io/websocket@v1.8.10/netconn.go:157 +0x2a
nhooyr.io/websocket.(*netConn).Read(0x90a00f0, {0x9180000, 0x8000, 0x8000})
.../go/pkg/mod/nhooyr.io/websocket@v1.8.10/netconn.go:145 …
```

Fix unaligned load error on 32-bit architectures

---

accept_test.go
close.go
conn.go
conn_test.go
mask.go
mask_asm.go
netconn.go
read.go
write.go
ws_js.go

the added test fails before this with
------------
i originally found this in D2 when i added tests for watching and --race started failing but the code seems to be purely confined in this library.
------
hacked together test, so if you accept it and want me to clean it up, i can. just seeing if this is legit.

fix closenow race

---

.github/workflows/static.yml
README.md

This PR fixes the coverage badge in the README by hosting the badge and static HTML on GitHub Pages.
We end up running an extra `./ci/test.sh` but I wanted to keep this simple for now.

Fix coverage

---

.github/workflows/static.yml

The static deploy failed: https://github.com/coder/websocket/actions/runs/10408927491/job/28827386982, it seems to have Go even without setup-go, but most likely the `bin` directory for `go install`ed tools wasn't set up in `$PATH`.

Add setup-go to static.yml

---

.github/workflows/static.yml

Trying to narrow down this really weird error by splitting up the two jobs: https://github.com/coder/websocket/actions/runs/10409069016/job/28827848583#step:5:96
```
--- FAIL: TestWasm (30.09s)
conn_test.go:371: wasm test binary failed: exit status 1:
Error: total length of command line and environment variables exceeds limit
at globalThis.Go.run (http://127.0.0.1:41105/wasm_exec.js:524:11)
at http://127.0.0.1:41105/:275:14
exit with status 1
FAIL	github.com/coder/websocket	16.603s
FAIL
```

Split coverage and deploy jobs in static.yml to avoid env issue

---

accept.go

OS-specific behaviour is not necessary. This PR replaces filepath.Match with path.Match and also updated the documentation to reflect that.
Closes #451

Replace filepath.Match with path.Match

---

accept.go
accept_test.go
hijack.go
hijack_go120_test.go

Since we rely on the connection not being hijacked too early (i.e. detecting the presence of http.Hijacker) to set headers, we must manually implement the unwrapping of the http.ResponseController. By doing so, we also retain Go 1.19 compatibility without build tags (still used in compat test, though).
Closes #455

accept: Add unwrapping for hijack like http.ResponseController

---

.github/workflows/ci.yml

Now, CI will only run on push to `master` and PRs to `master`.  Previously, it was running twice on each push to a PR branch, once for the PR to `master` and once for pushing to the PR branch.

chore: optimize ci

---

.github/workflows/ci.yml

The CI is currently failing with this error when trying to launch `TestWasm` with wasmbrowsertest:
No usable sandbox! If you are running on Ubuntu 23.10+ or another Linux distro that has disabled unprivileged user namespaces with AppArmor, see https://chromium.googlesource.com/chromium/src/+/main/docs/security/apparmor-userns-restrictions.md. Otherwise see https://chromium.googlesource.com/chromium/src/+/main/docs/linux/suid_sandbox_development.md for more information on developing with the (older) SUID sandbox. If you want to live dangerously and need an immediate workaround, you can try using --no-sandbox.
This change disables AppArmor in the CI to allow the sandbox to work.
Fixes #512
Closes #510

Disable AppArmor in CI to allow chrome sandbox

---

.github/workflows/daily.yml
.github/workflows/static.yml

AppArmor was disabled in CI workflows, but it was not disabled in the daily and static workflows.
References #512

ci: disable AppArmor on daily and static workflows

---

autobahn_test.go

Go 1.24 provides stricter checking that forbids passing a variable as a format string to Printf-like functions with no other arguments. Remove instances of this. See also:
https://tip.golang.org/doc/go1.24#vet

Fix build with Go 1.24

---

accept.go
conn.go
conn_test.go
dial.go
read.go

Add ping and pong received callbacks
This change adds two optional callbacks to both `DialOptions` and
`AcceptOptions`. These callbacks are invoked synchronously when a ping
or pong frame is received, allowing advanced users to log or inspect
payloads for metrics or debugging. If the callback needs to perform more
complex work or reuse the payload outside the callback, it is
recommended to perform processing in a separate goroutine.
The boolean return value of `OnPingReceived` is used to determine if the
subsequent pong frame should be sent. If `false` is returned, the pong
frame is not sent.
Tests confirm that the ping/pong callbacks are invoked as expected.
Fixes #246
Closes #307

Add ping and pong received callbacks

---

ci/test.sh

Using latest wasn't getting the latest version of wasmbrowsertest, so we're now using a specific commit.
Current version was failing due to timeouts, so we're updating to latest commit to see if it fixes the issue.

ci: update wasmbrowsertest to a specific commit

---

.github/workflows/ci.yml
.github/workflows/daily.yml
ci/lint.sh

Required until we update from Go 1.19.

ci: lock down staticcheck and govulncheck in lint.sh

---

accept.go
accept_test.go

This change aligns origin checks with RFC 6454 by adding scheme-aware matching.
Fixes #529

fix: match Origin scheme if defined in OriginPatterns

---

close.go
conn.go
read.go
write.go

This is a reworked version of https://github.com/coder/websocket/pull/501 with some minor improvements.
Closes https://github.com/coder/websocket/issues/411
Closes https://github.com/coder/websocket/pull/501

Use `context.AfterFunc()` instead of a goroutine to track timeouts
