coder/websocket

- .github/CONTRIBUTING.md
- .github/fmt/entrypoint.sh
- README.md
- accept.go
- datatype.go
- dial.go
- doc.go
- go.mod
- go.sum
- header.go
- header_test.go
- json.go
- opcode.go
- statuscode.go
- websocket.go
- websocket_test.go
This PR implements the client and server side handshakes.
> Implement handshake

- README.md
- accept.go
- datatype.go
- dial.go
- json.go
- opcode.go
- statuscode.go
- websocket.go
- websocket_test.go
> Improvements

- README.md
> Remove release badge

- accept.go
- example_test.go
- header.go
- header_test.go
- statuscode.go
- statuscode_string.go
- statuscode_test.go
- websocket.go
- websocket_test.go
With Cookie and CloseError unit tests
> Improve test coverage

- README.md
- doc.go
- example_echo_test.go
- example_test.go
- statuscode.go
- websocket.go
> Fixes for release

- README.md
> Have more honest performance comparison in README.md

- README.md
> Add Tatsu to companies section in README

- conn.go
- doc.go
- netconn.go
- websocket_js.go
> Add *Conn.CloseRead for WASM

- README.md
> Cleanup README language

- .github/CONTRIBUTING.md
- .github/workflows/ci.yml
> Upload coverage.html from test.sh as an artifact

- conn.go
- conn_test.go
> Fix concurrent read with close

- conn.go
> Fix race with c.readerShouldLock

- handshake.go
> Improve handshake to better match RFC

- example_test.go
> Add Example_crossOrigin

- wsjson/wsjson.go
> Less strict about message type of JSON payloads

- ci/all.sh
- write.go
> Fix deadlock introduced in v1.8.5

- netconn.go
> netconn.go: Prevent timer leakage

- conn_test.go
New try at fixing the issue mentioned in #468.
> Clean out env passed to wasmbrowsertest in TestWasm

- .github/workflows/static.yml
This reverts commit 0f14077dcfa84bb22fa4f83f84d9f0444c5accfe.
> Revert "Split coverage and deploy jobs in static.yml to avoid env issue"

- README.md
- accept.go
- internal/examples/chat/chat.go
- internal/examples/echo/server.go
> docs: Fix docs and examples related to r.Context() usage

- ci/fmt.sh
- ci/lint.sh
- go.mod
- internal/examples/go.mod
- internal/thirdparty/go.mod
- internal/thirdparty/go.sum
- **build: update to Go 1.23**
- **ci: update tools**
> build: update to Go 1.23
